CREATE TABLE IF NOT EXISTS authors (name TEXT PRIMARY KEY, pwd TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS files (
	name TEXT NOT NULL,
	url TEXT NOT NULL,
	owner TEXT REFERENCES authors (name) ON UPDATE CASCADE
);
